config/routes.rb
Rails.application.routes.draw do
  get 'pong/index'

  root :to => "visitors#index"

  get "pong", :to => 'pong#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pong_controller.rb
class PongController < ApplicationController
  def index
  	render :layout => "angular"
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pong_helper.rb
module PongHelper
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'NOOK Pong', pong_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/angular.html.slim
doctype html
html lang="en" ng-app="pong" 
  head
    meta charset="utf-8" 
      meta content="IE=Edge,chrome=1" http-equiv="X-UA-Compatible" 
        meta content="width=device-width, initial-scale=1.0" name="viewport" 
          title= content_for?(:title) ? yield(:title) : "NOOK Pong"
          = csrf_meta_tags
          = stylesheet_link_tag "application", :media => "all"
  body
    .navbar.navbar-default
      .container
        .navbar-header
          a.navbar-brand href="#" 
            h1
              a href="/"  Pong
        .navbar-collapse.collapse
          ul.nav.navbar-nav.navbar-right.user-panel-container
            li.active
              /! user info will go here soon
        /! /.nav-collapse
    #primary.container
      .row
        #main ng-view="" 
    /! /container

    div ng-controller="GamesController"
      div ng-repeat="game in games" 
        div class="result-container"
          div class="date"
            p Date: {{game.date}}
          div class="game"
            p Game: {{game.player1.name}} scored {{game.player1.score}} versus {{game.player2.name}} 
                who scored {{game.player2.score}}
    #f
      .container
        .row
          p Built by LogicWerx for NOOK Media LLC.
    = javascript_include_tag "application"

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Pong'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Pong'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/pong/index.html.slim
h1 Pong#index
p Find me in app/views/pong/index.html.slim

app/views/visitors/index.html.erb
<h3>Welcome</h3>